### ISSUE TITLE
I updated the code to use gpt-3.5-turbo model on my fork -- feel free to copy/paste

### ISSUE THREAD

**Issue by CaseySMiller** [openai/openai-quickstart-node#100]
### Describe the feature or improvement you're requesting

I updated the code to use GPT-3.5-turbo. Feel free to copy my code from my fork @ https://github.com/CaseySMiller/openai-quickstart-node

I also wasn't able to get .env variables from ./.env so changed it to ./.env.local

I updated the readme to reflect this.

### Additional context

- Updated the .env.example file name
- Updated readme to reflect .env change
- Changed to newest version of openai library in package.json
- Modified ./pages/api/generate.js to call createChatCompletion instead of the createCompletion method and pass it a correctly formatted object
- Happy copy/pasting ;)

**Comment by logankilpatrick** [comment]
I am taking a pass at this in a new PR, thanks for the flag!
