### ISSUE TITLE
The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations

### ISSUE THREAD

**Issue by 971758118** [openai/openai-quickstart-node#127]
### Describe the bug

404 {
  error: {
    message: 'The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations',
    type: 'invalid_request_error',
    param: null,
    code: 'model_not_found'
  }
}

### To Reproduce

1. npm run dev
2. open http://localhost:3000
3. input something

**Comment by logankilpatrick** [comment]
I am taking a pass at this in a new PR, thanks for the flag!
