### ISSUE TITLE
HI i was intreacting with ChatGpt and found an bug ,kindly check through it

### ISSUE THREAD

**Issue by Praveen-kumar-1604** [openai/openai-quickstart-node#22]
![image](https://user-images.githubusercontent.com/111982534/206407926-bbbdf13e-164b-4f31-a083-f234a8bdd8a9.png)

As you can see abouve the text overlaps and escapes the continer as soon as a large text appears in the code container

**Comment by schnerd** [comment]
Thanks! If you are still experiencing this issue, feel free to report it in the openai discord (see the link in the sidebar of ChatGPT). The issue tracker here is for issues specifically with the openai-quickstart-node project.
