### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Sheikh-JamirAlam** [openai/openai-quickstart-node#25]
I am running the project locally but whenever I tried clicking "Generate names" but it shows this error. Anyone knows how to fix this?
![image](https://user-images.githubusercontent.com/48979376/206766453-6b2290c3-1192-4ee0-ab2a-f9a718fa7f5b.png)

**Comment by kwello-alexhicks** [comment]
I'm getting exactly the same thing... did you get anywhere with your issue @Sheikh-JamirAlam

**Comment by Sheikh-JamirAlam** [comment]
Seems like my quota has exceeded for making request to the API. No idea how to work around it though. @kwello-alexhicks

**Comment by kwello-alexhicks** [comment]
My issue doesn't appear to be related to the API, reviewing the generate Response is the same as yours that it is not a valid JSON reponse

`{
    "props": {
        "pageProps": {
            "statusCode": 500
        }
    },
    "page": "/_error",
    "query": {
        "__NEXT_PAGE": "/api/generate"
    },
    "buildId": "development",
    "isFallback": false,
    "err": {
        "name": "Error",
        "message": "Request failed with status code 401",
        "stack": "Error: Request failed with status code 401\n    at createError (/Users/XXXXX/openai-quickstart-node/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/Users/XXXXX/openai-quickstart-node/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/Users/XXXXX/openai-quickstart-node/node_modules/axios/lib/adapters/http.js:322:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
    },
    "gip": true,
    "scriptLoader": []
}`

**Comment by kwello-alexhicks** [comment]
@Sheikh-JamirAlam Ok, so i opened a new terminal, ran 

`npm run build`
`npm run start`
`npm run dev`

Then I can successfully run the application on new port 3001

Bit odd, or missing step in the documentation?

**Comment by Sheikh-JamirAlam** [comment]
Yes the API is not generating a JSON file.
Do you run the "npm run start" and "npm run dev" commands in different terminals?

**Comment by kwello-alexhicks** [comment]
@Sheikh-JamirAlam correct order, from the same terminal (after killing the faulty terminal) is:

npm run start
npm run build
npm run dev

This now works successfully for me

**Comment by Sheikh-JamirAlam** [comment]
@kwello-alexhicks  Now I am facing with this error. I ran npm run build and it still is the same. Can you show your terminal if thats ok?
![image](https://user-images.githubusercontent.com/48979376/206870809-3cc76800-a1f4-4d5d-b812-57ac0e4a88ff.png)

**Comment by TheFrank86** [comment]
Took my a while but my similar issue of errors was that I put my API Key in ".env.example" when it of course needed to be in ".env" instead.

**Comment by AlbaChloe** [comment]
> 

same situation, thx

**Comment by Sanan4li** [comment]
> > 
> 
> same situation, thx

Thanks. Did the same mistake.

**Comment by Sheikh-JamirAlam** [comment]
@Sanan4li Can you tell me which commands you are using to run it locally?

**Comment by neocybereth** [comment]
<img width="699" alt="Screen Shot 2022-12-23 at 10 21 40 PM" src="https://user-images.githubusercontent.com/14209806/209309108-78384e8b-a177-4c9a-bd57-87253de88f25.png">


I'm still getting the issue even after running: 

npm run start
npm run build
npm run dev

@kwello-alexhicks is this still working on your end?

@Sheikh-JamirAlam  are you still having trouble?

**Comment by neocybereth** [comment]
@jeevnayak do you know any potential fixes?

**Comment by AlbaChloe** [comment]
> <img alt="Screen Shot 2022-12-23 at 10 21 40 PM" width="699" src="https://user-images.githubusercontent.com/14209806/209309108-78384e8b-a177-4c9a-bd57-87253de88f25.png">
> 
> I'm still getting the issue even after running:
> 
> npm run start npm run build npm run dev
> 
> @kwello-alexhicks is this still working on your end?
> 
> @Sheikh-JamirAlam are you still having trouble?

no need to use command line, just check your env filename, the repo's original env filename is ".env.example",  rename it with ".env" will work : )

**Comment by neocybereth** [comment]
@AlbaChloe ive already done that, but no dice. Seems the 500 errors coming from elsewhere

**Comment by Sheikh-JamirAlam** [comment]
@neocybereth Yeah same, its not because of the .env file. As the error shows the API is returning a HTML file which was supposed to be a json.
@AlbaChloe Is it working for you locally?

**Comment by AlbaChloe** [comment]
![image](https://user-images.githubusercontent.com/82038040/209332171-bc247d8f-6e5c-4d23-ab81-17c458ad4b1e.png)
![image](https://user-images.githubusercontent.com/82038040/209332578-4ac5ec10-3dd4-4524-85e6-9798c55137ec.png)
@Sheikh-JamirAlam yep, my local file works fine after I change the filename to ".env", and before that, I got the same error
@neocybereth  sorry, maybe elsewhere I don't know, hope others can help you

**Comment by Sheikh-JamirAlam** [comment]
@AlbaChloe Did you maybe change the dependency versions or it worked just like that?

**Comment by AlbaChloe** [comment]
@Sheikh-JamirAlam nope, I've never changed the dependencies, just run "npm install" to install the requirements

**Comment by schnerd** [comment]
I added some error handling logic (see #30) which should surface error messages returned by the API or due to misconfigured environment variables.

@neocybereth want to pull the latest version and give it a try?

**Comment by neocybereth** [comment]
Yup, will do that now!

**Comment by neocybereth** [comment]
@schnerd is it in version 3.1.0 of the `openai` package?

**Comment by neocybereth** [comment]
<img width="876" alt="Screen Shot 2022-12-24 at 2 15 04 PM" src="https://user-images.githubusercontent.com/14209806/209416596-1bc2264b-93d1-4982-b5ec-6f86e22baea5.png">

Here's what I got @schnerd

**Comment by neocybereth** [comment]
<img width="540" alt="Screen Shot 2022-12-24 at 2 18 20 PM" src="https://user-images.githubusercontent.com/14209806/209416644-fb40be4d-8d17-4127-ad7d-6227d2853785.png">

Welp seems that did the trick now @schnerd

**Comment by schnerd** [comment]
👍 

I'm going to close this issue for now – the frontend should be surfacing more detailed error messages. If anyone continues to see errors where it's unclear how to resolve them, please feel free to open a separate issue!
