### ISSUE TITLE
Dark and Light theme toggler button feature

### ISSUE THREAD

**Issue by hparashar27** [openai/openai-quickstart-node#35]
### Describe the feature or improvement you're requesting

Implementation of Dark and Light theme feature gives a better look

**Comment by Naseem010** [comment]
Hi if you want to put dark mode switch button then I can take care of it.
it will look like it.
![Screenshot_20230120_002531](https://user-images.githubusercontent.com/77022255/213534990-79a50b2e-ee8c-4d52-9bdd-c3df870574e5.png)
![Screenshot_20230120_002559](https://user-images.githubusercontent.com/77022255/213534996-02befaef-1dbf-4b9c-8478-c5b8045ff647.png)

**Comment by schnerd** [comment]
Thanks folks! The goal of this quickstart application is to be the simplest code possible that demonstrates building a node-based app that connects to our API. Adding additional unrelated features like dark mode might distract new developers who are trying to read and understand the code, so I think we probably want to pass on adding this for now.
