### ISSUE TITLE
[403 Forbidden]The OpenAI API can only be accessed over HTTPS.

### ISSUE THREAD

**Issue by lyf61** [openai/openai-quickstart-node#48]
### Describe the bug

request header
Request URL: http://localhost:3000/api/generate
Request Method: POST
Status Code: 403 Forbidden

response
{"error":{"message":"The OpenAI API can only be accessed over HTTPS. You should access https://api.openai.com rather than the current URL.","type":"invalid_request_error"}}

### To Reproduce

the alert showed after clicked on the Generate names button

### OS

macOS

### Node version

v14.18.1

**Comment by logankilpatrick** [comment]
Can you share the full request you are passing in?

**Comment by christopherwolf1** [comment]
I am also getting this error (macOS); running the openai-quickstart-node codebase with no modification

Relevant request in my case is this part of the try block

`try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ animal: animalInput }),
      });`

Interestingly, I have my own code that uses a POST request and *doesn't* trigger the 403 error; there shouldn't really be any difference and I would expect the official quickstart to work out of the box

**Comment by nitin-787** [comment]
> 

I am also getting the same error, but while testing in postman it just works fine

here is my code 

Note : I also tried using https instead http

`import 'dart:convert';

import 'package:chatgpt/constants/api_consts.dart';
import 'package:http/http.dart' as http;

class ApiService {
  static Future<void> getModels() async {
    try {
      var response = await http.get(
        Uri.parse("$BASE_URL/models"),
        headers: {'Authorization': 'Bearer $API_KEY'},
      );

      Map jsonResponse = jsonDecode(response.body);
      print("response $jsonResponse");
    } catch (error) {
      print("error $error");
    }
  }
}
`

**Comment by lyf61** [comment]
problem solved after i turn off VPN.

**Comment by nitin-787** [comment]
> problem solved after i turn off VPN.

lol
