### ISSUE TITLE
The readme Docs should contain a section for the contributors

### ISSUE THREAD

**Issue by cleverhare** [openai/openai-quickstart-node#70]
## Description
OpenAI is one of the most significant companies in the world. SO every contributor contributing to the OpenAI-Quickstart website has a dream in mind that the contributor's GitHub profile gets visible to the people coming to this repo.

## What is the problem?
So, the current Readme documentation file doesn't contain any section where we can directly see the peoples who contributed to the repo. and because of that a lot of people are losing opportunities.

## How can we address it?
So, I will write an MD to add a section and add all the GitHub usernames who have contributed to the existing repo. And I will make sure this contributing peoples section is after everything or its in the last section of readme documentation

## Why is it important?
It important because:-

- The contributors would be much happy if they see their profile on the home page of repo. and it will motivate new contributors to contribute to the repo
- it will be really very good for the company as well because they are taking care of contributors.

## Who needs this?
Everyone using this

When should this happen (use version numbers if needed)?
Once this issue sounds helpful to the viewer.

So if the issue sounds helpful, do assign me for this issue and I will be really very happy to contribute to it ;).

**Comment by logankilpatrick** [comment]
Thanks for the suggestion!
