### ISSUE TITLE
connect ETIMEDOUT 31.13.70.33:443

### ISSUE THREAD

**Issue by 583175694** [openai/openai-quickstart-node#79]
### Describe the bug

When I npm run dev and request the interface, this error is reported, and I can't ping 31.13.94.36, how should I solve this problem?

### To Reproduce

1.npm install
2.npm run dev
3.connect ETIMEDOUT 31.13.70.33:443

**Comment by jk-zhang** [comment]
I had the same problem

`Error with OpenAI API request: connect ETIMEDOUT 31.13.90.19:443`

**Comment by Abandon99** [comment]
if you are in China, may this can help you:
https://github.com/openai/openai-quickstart-node/issues/78

**Comment by JinliG** [comment]
If you are in China and have a available provy, you can resolve this prolem with this:
```js
openai.createCompletion({ ...params }, {
          httpsAgent: tunnel.httpsOverHttp({
                    proxy: {
                              host: 'xx.xx.xx',
                              port: xx,
                    }
          })
});
```

**Comment by lpbottle** [comment]
> 

I have tried to use your solution to solve the problem, but it didn't work and still returned 'An error occurred during your request'.

**Comment by lpbottle** [comment]
> If you are in China and have a available proxy, you can resolve this prolem by this:
> 
> ```js
> openai.createCompletion({ ...params }, {
>           httpsAgent: tunnel.httpsOverHttp({
>                     proxy: {
>                               host: 'xx.xx.xx',
>                               port: xx,
>                     }
>           })
> });
> ```

I have tried to use your solution to solve the problem, but it didn't work and still returned 'An error occurred during your request'.

**Comment by wang-xiaowu** [comment]
> If you are in China and have a available proxy, you can resolve this prolem by this:
> 
> ```js
> openai.createCompletion({ ...params }, {
>           httpsAgent: tunnel.httpsOverHttp({
>                     proxy: {
>                               host: 'xx.xx.xx',
>                               port: xx,
>                     }
>           })
> });
> ```


it worked
```js
const {Configuration, OpenAIApi} = require("openai");
const tunnel = require('tunnel');
const axios = require('axios');
exports.openai = (opts = {}) => {
    const configuration = new Configuration({
        apiKey: opts.apiKey,

    });
    const client = axios.create({
        httpsAgent: tunnel.httpsOverHttp({
            proxy: {
                host: '127.0.0.1',
                port: 7890,
            }
        })
    });
    const openai = new OpenAIApi(configuration, configuration.basePath, client);
    return async (ctx, next) => {
        ctx.openai = openai;
        await next();
    };
};
```

**Comment by fredmanxu** [comment]
> 

Don't forget to `npm install tunnel`

**Comment by 2019geguangpu** [comment]
After config the proxy，i got an error. Here's the error 'Error with OpenAI API request: tunneling socket could not be established, cause=socket hang up'

**Comment by 2019geguangpu** [comment]
> After config the proxy，i got an error. Here's the error 'Error with OpenAI API request: tunneling socket could not be established, cause=socket hang up'
It seems like  that i must config username and password. But, that's my guess.

**Comment by Zheap** [comment]
> > If you are in China and have a available proxy, you can resolve this prolem by this:
> > ```js
> > openai.createCompletion({ ...params }, {
> >           httpsAgent: tunnel.httpsOverHttp({
> >                     proxy: {
> >                               host: 'xx.xx.xx',
> >                               port: xx,
> >                     }
> >           })
> > });
> > ```
> 
> it worked, you can find it in my project: https://github.com/behappy-project/behappy-chatgpt-assistant/blob/main/lib/openai.js
> 
> ```js
> const {Configuration, OpenAIApi} = require("openai");
> const tunnel = require('tunnel');
> const axios = require('axios');
> exports.openai = (opts = {}) => {
>     const configuration = new Configuration({
>         apiKey: opts.apiKey,
> 
>     });
>     const client = axios.create({
>         httpsAgent: tunnel.httpsOverHttp({
>             proxy: {
>                 host: '127.0.0.1',
>                 port: 7890,
>             }
>         })
>     });
>     const openai = new OpenAIApi(configuration, configuration.basePath, client);
>     return async (ctx, next) => {
>         ctx.openai = openai;
>         await next();
>     };
> };
> ```

thks
