### ISSUE TITLE
Server error when deploy to Heroku

### ISSUE THREAD

**Issue by melboo** [openai/openai-quickstart-node#8]
Hi,

I wanted to deploy the example on a Heroku server but got an error.  Any ideas?

`Server Error
TypeError: (0 , react_jsx_dev_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxDEV) is not a function`

**Comment by CavHack** [comment]
You need to run webpack in suse

**Comment by schnerd** [comment]
This application is a fairly simple [next.js](https://nextjs.org/) app, so I'd look into issues and documentation related to running next.js in Heroku. If this continues to be an issue, please feel free to open up a separate issue with exact replication steps!
